rvm:
  - 1.9.3 # (current default)
  - 2.0.0
branches:
  only:
    - master
    - rails_4
before_script:
  - "psql -c 'create database birthday_plugin_test;' -U postgres"
  - "mysql -e 'create database birthday_plugin_test;'"
  - "gem install rails -v 3.2.14"
  - "gem install rails -v 4.0.0"
env:
  - DB=mysql RAILS=4.0.0
  - DB=postgres RAILS=4.0.0
  - DB=mysql RAILS=3.2.14
  - DB=postgres RAILS=3.2.14
