mysql:
  adapter: mysql
  database: birthday_plugin_test
  username: 
  encoding: utf8
postgres:
  adapter: postgresql
  database: birthday_plugin_test
  username: postgres
sqlite:
  adapter: sqlite3
  database: db/birthday_plugin_test.sqlite3
  pool: 5
  timeout: 5000